version: '2.0'

services:
  database:
    image: mysql:latest
    container_name: 'database'
    ports:
      - "3306:3306"
    volumes:
        - /mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: cloud
      restart: on-failure

  frontend:
    build: 'frontend/'
    image: 'frontend:1.0'
    ports:
      - '8080:8080'
      -
  backend:
    image: app
    restart: on-failure
    depends_on:
      - database
    ports:
      - '8090:8090'

