version: '2.0'

services:

  database:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: mysql
    #      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "3306:3306"

  backend:
    container_name: backend
    build: ./
    image: cloudapp:latest
    restart: always
    environment:
      spring_datasource_url: jdbc:mysql://localhost:3306/mysql
    ports:
      - "8090:8090"
    depends_on:
      - database

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name:   frontend
    image: cloudfront:latest
    ports:
      - "8080:8080"






